
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Include
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Device/ST/STM32F1xx/Include
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver/Inc
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver

subdir-y += Src

obj-y += stm32f1xx_it.o
obj-y += system_stm32f1xx.o

include $(RULE_DIR)/rules.mk
